### ISSUE TITLE
Прекращается работа скрипта при невозможности прочитать данные

### ISSUE THREAD

**Issue by max-sparker** [0x566164696D/mt_backup_ng#1]
Хороший скрипт, использую его для сбора бекапов с девайсов и сохраняю их в git репозиторий - после чего можно легко отслеживать изменения. Спасибо за готовое решение.

Учитывая, что у Вас используется более 250 MikroTik девайсов в сети - возможно сталкивались с тем, что иногда бывает - железка находится в полу зависшем состоянии. 
Доступ до нее вроде есть, но невозможно с нее прочитать данные никаким образом. Помогает только перезагрузка девайса.

Проблема в чем, скрипт по ssh подключается к такой железке, пытается прочитать имя и серийник - в ответ получить ничего не может, в итоге вываливается ошибка и скрипт останавливается, не опросив железки далее по списку.

В консоле, если вручную попытаться получить например имя девайса вываливается такое:
[admin@Hm-Router] > \system identity print
action timed out - try again, if error continues contact MikroTik support and se
nd a supout file (13)

Хорошо бы сделать какую-то проверку на такие ошибки и в случае неудачи - продолжать работу скрипта, опрашивая последующие микротики.

Спасибо за внимание! :+1:

**Comment by 0x566164696D** [comment]
Здравствуйте, спасибо за отзыв и использование скрипта ) Действительно
скрипт нужно доработать, у меня есть еще несколько идей как его улучшить, в
том числе решить эту проблему. Постараюсь найти время в эти праздники.
С наступающим!

29 декабря 2014 г., 14:04 пользователь max-sparker <notifications@github.com

**Comment by 0x566164696D** [comment]
Здравствуйте, теперь скрипт продолжает свою работу если роутер "подвис". Добавлено еще несколько фич, подробности в changelog.

**Comment by max-sparker** [comment]
Спасибо. Проверил - все работает.
Немножко его подкорректировал под себя, у меня список ip берется с БД MySQL.
В функции выполнения резервного копирования добавил такое:

# подключаемся к базе данных

db = MySQLdb.connect(host="localhost", user="user", passwd="password", db="radius")

# формируем курсор, с помощью которого можно исполнять SQL-запросы

cursor = db.cursor()

# запрос для получения списка IP

sql = """SELECT nasname, port FROM radnas WHERE"""

# выполняем запрос

cursor.execute(sql)

# получаем результат выполнения запроса

data =  cursor.fetchall()
for rec in data:
    # извлекаем данные из записей - в том же порядке, как и в SQL-запросе
    nasname, port  = rec
    ip=nasname

И далее уже по тому же алгоритму:
    if test_port(ip,port)==True:
    и т.д.

У меня авторизация на тики происходит через RADIUS сервер и все устройства хранятся в БД, поэтому так для меня более удобнее будет.

Думаю можно подключение к БД также добавить в скрипт с настройками конфигурации

**Comment by max-sparker** [comment]
Функцию ssh_get_file() необходимо тоже сделать проверку на ошибки
бывает такое, что файл не создается бекап на девайсе, и если файла на тике не существует - то скрипт прекращает свою работу с ошибкой.

**Comment by 0x566164696D** [comment]
Исправлено, уже давно )
